
[[_Usage]]
= Usage

The following sections describe how you may use this plugin in a project.

== Configuration

The plugin's <<_modules, module>> registers a `{api_kryonet_handler}` helper class that defines the base contract
for issuing Kryonet calls using an appropriate client class. This helper class has the following methods

[source,java,options="nowrap"]
.griffon.plugins.kryonet.KryonetHandler.java
----
include::{path_griffon_kryonet_core}/src/main/java//griffon/plugins/kryonet/KryonetHandler.java[tags=methods,indent=0]
----

The following properties must be defined:

[horizontal]
host:: The host on which remote objects haven been registered. String. Default `localhost`.
port:: The port on which objects were exported. Integer. Default `54555`.
timeout:: Connection timeout. Boolean. Default `5000`.

These methods will create a new client when invoked unless you define an `id:` attribute. When this attribute is supplied
the client will be stored in a cache managed by their respective storage classes (`{api_kryonetclient_storage}`).

You can inject an instance of `{api_kryonet_handler}` anywhere it's needed using `@Inject`.

The `{api_kryonetclient_callback}` callback is defined using a functional interface approach, which means you can apply
lambda expressions if running with JDK8+ or closures if running Groovy.

[source,java,options="nowrap"]
.griffon.plugins.kryonet.KryonetCallback.java
----
include::{path_griffon_kryonet_core}/src/main/java/griffon/plugins/kryonet/KryonetClientCallback.java[lines=30..-1]
----

Instances of type `griffon.plugins.kryonet.KryoConfigurer` should be provided using module bindings. This type is
responsible for registering classes with the `com.esotericsoftware.kryo.Kryo` instance from the Client.

[source,java,options="nowrap"]
.griffon.plugins.kryonet.KryoConfigurer.java
----
include::{path_griffon_kryonet_core}/src/main/java/griffon/plugins/kryonet/KryoConfigurer.java[lines=26..-1]
----

At least one instance of `griffon.plugins.kryonet.KryonetClientListener` must be provided by a module binding. This type
is responsible for handling events and data sent from the server.

== Example

The following is a trivial usage of the `{api_kryonet_handler}` inside a service

[source,java,options="nowrap"]
.CommandService.java
----
include::{path_griffon_kryonet_core}/src/test/groovy/griffon/plugins/kryonet/CommandService.java[lines=18..-1]
----

Here's the Groovy version of the same service

[source,groovy,options="nowrap"]
.GroovyCommandService.groovy
----
include::{path_griffon_kryonet_core}/src/test/groovy/griffon/plugins/kryonet/GroovyCommandService.groovy[lines=18..-1]
----

== AST Transformation

You can apply the `{api_kryonet_aware}` AST transformation on any class. This injects the behavior of `{api_kryonet_handler}`
into said class.

== DSL Descriptors

This plugin provides DSL descriptors for Intellij IDEA and Eclipse (provided you have the Groovy Eclipse plugin installed).
These descriptors are found inside the `griffon-kryonet-groovy-compile-{project-version}.jar`, with locations

 * dsdl/griffon_kryonet.dsld
 * gdsl/griffon_kryonet.gdsl
